global:
  namespace: a2d2 

persistentVolumeClaim:
  efs: "efs-a2d2"
  fsx: "fsx-a2d2"

a2d2:
  name: a2d2-rosbridge
  image:
    uri: 'XXXXXXXXXXXX.dkr.ecr.xx-xxxx-x.amazonaws.com/mozart-melodic-bionic:0.9' 
    policy: Always
  serviceAccount:
    name: a2d2-rosbridge-sa
    roleArn: 

command:
  path: '/usr/local/bin/rosbridge.sh'

rosbridge:
  port: 9090 
  target_port: 9090 
  internal: "false"
  source_cidr: "0.0.0.0/0"
