---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.a2d2.serviceAccount.roleArn }}
  name: {{ .Values.a2d2.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.a2d2.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "false"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "false"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "{{ .Values.rosbridge.internal }}"
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.rosbridge.port }} 
    targetPort:  {{ .Values.rosbridge.target_port }}
  selector:
    app: {{ .Values.a2d2.name }}
  type: LoadBalancer
  loadBalancerSourceRanges:
  - {{ .Values.rosbridge.source_cidr }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.a2d2.name }}
  labels:
    app: {{ .Values.a2d2.name }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: {{ .Values.a2d2.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.a2d2.name }}
    spec:
      serviceAccountName: {{ .Values.a2d2.serviceAccount.name }}
      volumes:
      - name: fsx
        persistentVolumeClaim:
           claimName: fsx-a2d2
      - name: efs 
        persistentVolumeClaim:
           claimName: efs-a2d2
      - name: tmp
        emptyDir: {}
      containers:
      - name: {{ .Values.a2d2.name }} 
        image: {{ .Values.a2d2.image.uri }} 
        imagePullPolicy: {{ .Values.a2d2.image.policy }}
        command:
        - {{ .Values.command.path }} 
        volumeMounts:
        - mountPath: /fsx
          name: fsx 
        - mountPath: /efs
          name: efs 
        - mountPath: /tmp
          name: tmp
