---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: 
  name: efs-a2d2-sa 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stage-data 
data:
  stage-data.sh: |
    mkdir -p $STAGE_DIR
    aws s3 cp --recursive s3://$S3_BUCKET/$S3_PREFIX $STAGE_DIR
---
apiVersion: v1
kind: Pod
metadata:
  name: stage-efs-a2d2
spec:
  restartPolicy: Never
  serviceAccountName: efs-a2d2-sa
  volumes:
  - name: efs
    persistentVolumeClaim:
      claimName: efs-a2d2 
  - name: config
    configMap:
      defaultMode: 420
      items:
      - key: stage-data.sh
        mode: 365
        path: stage-data.sh
      name: stage-data 
  containers:
  - name: stage-data
    env:
    - name: S3_BUCKET
      value: 
    - name: S3_PREFIX
      value: a2d2/camera_lidar 
    - name: STAGE_DIR 
      value: /efs/a2d2/camera_lidar
    command:
    -  sh 
    - /etc/config/stage-data.sh
    image: amazon/aws-cli # image with aws cli support 
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /etc/config
      name: config
    - mountPath: /efs
      name: efs
